services:
    payement_file_parser:
        class: Interne\FinancesBundle\Utils\PayementFileParser

    finances_statistics:
        class: Interne\FinancesBundle\Controller\StatisticsController
        arguments:
            - @doctrine.orm.entity_manager

    finances_printer:
        class: Interne\FinancesBundle\Controller\PrintController
        arguments:
            - @doctrine.orm.entity_manager
            - @parametres
            - @pdf

    # Twig
    # Extensions twig qui permettent de mettre en place des filtres
    # personnalisés
    app.twig.finances_extension:
        class: Interne\FinancesBundle\Twig\FinancesExtension
        tags:
            - { name: twig.extension }