language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer install --dev
  - cp app/config/parameters.yml.dist app/config/parameters.yml

script: phpunit -c app/

notifications:
  email:
    - netbs@sauvabelin.ch