language: php

php:
  - 5.5.9

before_script:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml

script: phpunit -c app/

notifications:
  email:
    - netbs@sauvabelin.ch