<?php

namespace AppBundle\Repository;

/**
 * FamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleRepository extends Repository
{
    /**
     * @param array $idArray
     * @return \Doctrine\ORM\QueryBuilder
     *
     * todo a voir si cette fonction est vraiement utilisée qq part
     */
    public function queryByIds($idArray)
    {
        $query = $this->createQueryBuilder('f')
            ->where('f.id IN (:id)')
            ->setParameter('id', $idArray);
        return $query;
    }

}
