# Elasticsearch Configuration
fos_elastica:
    clients:
        default: { host: "%elastic_host%", port: "%elastic_port%" }
    indexes:
        search:
            types:
                membre:
                    mappings:
                        prenom: ~
                        famille: ~
                        naissance: ~
                        remarques: ~
                        numeroBs: ~
                        sexe: ~
                        attributions:
                            type: "nested"
                            properties:
                                groupe: ~
                                fonction: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Membre
                        provider: ~
                        listener: ~
                        finder: ~
                famille:
                    mappings:
                        nom: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Famille
                        provider: ~
                        listener: ~
                        finder: ~
                groupe:
                    mappings:
                        nom: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Groupe
                        provider: ~
                        listener: ~
                        finder: ~
        finances:
            types:
                creances_to_membre:
                    mappings:
                        id: ~
                        titre: ~
                        remarque: ~
                        montantEmis: ~
                        montantRecu: ~
                        dateCreation: { type: date }
                        facture:
                            type: "nested"
                            properties:
                                id: ~
                    persistence:
                        driver: orm
                        model: Interne\FinancesBundle\Entity\CreanceToMembre
                        provider: ~
                        listener: ~
                        finder: ~
                creances_to_famille:
                    mappings:
                        id: ~
                        titre: ~
                        remarque: ~
                        montantEmis: ~
                        montantRecu: ~
                        dateCreation: { type: date}
                        facture:
                            type: "nested"
                            properties:
                                id: ~
                    persistence:
                        driver: orm
                        model: Interne\FinancesBundle\Entity\CreanceToFamille
                        provider: ~
                        listener: ~
                        finder: ~