# Elasticsearch Configuration
fos_elastica:
    clients:
        default: { host: "%elastic_host%", port: "%elastic_port%" }
    indexes:
        search:
            types:
                membre:
                    mappings:
                        prenom: ~
                        famille: ~
                        naissance: ~
                        remarques: ~
                        numeroBs: ~
                        sexe: ~
                        attributions:
                            type: "nested"
                            properties:
                                groupe: ~
                                fonction: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Membre
                        provider: ~
                        listener: ~
                        finder: ~
                famille:
                    mappings:
                        nom: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Famille
                        provider: ~
                        listener: ~
                        finder: ~
                groupe:
                    mappings:
                        nom: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Groupe
                        provider: ~
                        listener: ~
                        finder: ~
        finances:
            types:
                creances_to_membre:
                    mappings:
                        id: ~
                        titre: ~
                        remarque: ~
                        montantEmis: ~
                        montantRecu: ~
                        isFactured:
                            type: boolean
                        isPayed:
                            type: boolean
                        dateCreation: { type: date }
                        facture:
                            type: "nested"
                            properties:
                                id: { type: integer }
                        membre:
                            type: "nested"
                            properties:
                                prenom: { type: string }
                                nom: { type: string }
                    persistence:
                        driver: orm
                        model: Interne\FinancesBundle\Entity\CreanceToMembre
                        provider: ~
                        listener: ~
                        finder: ~
                creances_to_famille:
                    mappings:
                        id: ~
                        titre: ~
                        remarque: ~
                        montantEmis: ~
                        montantRecu: ~
                        isFactured:
                            type: boolean
                        isPayed:
                            type: boolean
                        dateCreation: { type: date}
                        facture:
                            type: "nested"
                            properties:
                                id: { type: integer }

                        famille:
                            type: "nested"
                            properties:
                                nom: { type: string }
                    persistence:
                        driver: orm
                        model: Interne\FinancesBundle\Entity\CreanceToFamille
                        provider: ~
                        listener: ~
                        finder: ~
                factures_to_membre:
                    mappings:
                        id: ~
                        montantEmis: ~
                        montantEmisCreances: ~
                        montantEmisRappels: ~
                        nombreRappels: ~
                        dateCreation: { type: date}
                        datePayement: { type: date}
                        montantRecu: ~
                        creances:
                            type: "nested"
                            properties:
                                titre: ~
                                montantEmis: ~
                                dateCreation: { type: date}
                        rappels:
                            type: "nested"
                            properties:
                                montantEmis: ~
                                dateCreation: { type: date}
                        membre:
                            type: "nested"
                            properties:
                                prenom: { type: string }
                                nom: { type: string }
                    persistence:
                        driver: orm
                        model: Interne\FinancesBundle\Entity\FactureToMembre
                        provider: ~
                        listener: ~
                        finder: ~
                factures_to_famille:
                    mappings:
                        id: ~
                        montantEmis: ~
                        montantEmisCreances: ~
                        montantEmisRappels: ~
                        nombreRappels: ~
                        dateCreation: { type: date}
                        datePayement: { type: date}
                        montantRecu: ~
                        creances:
                            type: "nested"
                            properties:
                                titre: ~
                                montantEmis: ~
                                dateCreation: { type: date}
                        rappels:
                            type: "nested"
                            properties:
                                montantEmis: ~
                                dateCreation: { type: date}
                        famille:
                            type: "nested"
                            properties:
                                nom: { type: string }
                    persistence:
                        driver: orm
                        model: Interne\FinancesBundle\Entity\FactureToFamille
                        provider: ~
                        listener: ~
                        finder: ~