# Monolog configuration
services:

    # This binds the onFLush doctrine event on our data logging listener
    data.change.listener:
        class: AppBundle\EventListener\LogOnChangeListener
        arguments:
            - @security.token_storage
            - @session
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }
