imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: search.yml }
    - { resource: log.yml }
    - { resource: doctrine_extensions.yml }

#définition des parametres fixes lié a AppBundle
app:
    upload_path: %kernel.root_dir%/../uploads

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    serializer:
        enabled: true
    profiler:
        collect: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        parametreService: "@parametres"
        #Service d'appel des liste dans twig
        list_caller: "@list_caller"
        #service de generation des menu. Permet d'obtenir les routes liée aux annotations @menu
        menu: "@menu"
    form:
        resources:
            - 'Templates/Form/Widgets/default_widgets.html.twig'
            - 'Templates/Form/Widgets/famille_value_widget.html.twig'
            - 'Templates/Form/Widgets/datepicker_widget.html.twig'
            - 'Templates/Form/Widgets/semantic_widget.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - AppBundle
        - InterneSecurityBundle
        - InterneGalerieBundle
        - InterneOrganisationBundle
        - InterneSeanceBundle
    write_to:       %kernel.root_dir%/../web/static/

    #java: /usr/bin/java
    filters:
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        jquery: %kernel.root_dir%/../vendor/components/jquery/jquery.min.js


# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                server_version: "%database_server_version%"
                mapping_types:
                    enum: string
            fichier: # connexion aux table de l'ancien fichier...
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   %database_name%
                user:     "%database_user%"
                password: "%database_password%"


        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:   default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
            fichier:
                connection:       fichier #base de donnée utilisée pour le transfert depuis l'ancien fichier



# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool: # command d'envoi des emails: php app/console swiftmailer:spool:send --env=dev
        type: file
        path: "%kernel.cache_dir%/swiftmailer/spool"
    delivery_address:  dev.sauvabelin@gmail.com # Option de Dév. qui permet de réaiguiller tout les mails sur cette adresse.

fos_rest:
    body_listener: true # to receive json encoded requests
    routing_loader:
        default_format: json
        include_format: false
