# Elasticsearch Configuration
fos_elastica:
    clients:
        default: { host: "%elastic_host%", port: "%elastic_port%" }
    indexes:
        search:
            types:
                membre:
                    mappings:
                        prenom: ~
                        famille:
                            type: "nested"
                            properties:
                                id: { type: integer }
                                nom: ~
                        naissance:
                            type: date
                        remarques: ~
                        numeroBs: ~
                        sexe: ~
                        attributions:
                            type: "nested"
                            properties:
                                groupe: ~
                                fonction: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Membre
                        provider: ~
                        listener: ~
                        finder: ~
                        repository: AppBundle\Search\Membre\MembreRepository
                famille:
                    mappings:
                        nom: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Famille
                        provider: ~
                        listener: ~
                        finder: ~
                groupe:
                    mappings:
                        nom: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Groupe
                        provider: ~
                        listener: ~
                        finder: ~
        finances:
            types:
                creances:
                    mappings:
                        id: ~
                        titre: ~
                        remarques: ~
                        montantEmis: ~
                        montantRecu: ~
                        isFactured: { type: boolean }
                        isPayed: { type: boolean }
                        dateCreation: { type: date }
                        datePayement: { type: date }
                        facture:
                            type: "nested"
                            properties:
                                id: { type: integer }
                        debiteur:
                            type: "nested"
                            properties:
                                getOwnerAsString: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Creance
                        provider: ~
                        listener: ~
                        finder: ~
                        repository: AppBundle\Search\Creance\CreanceRepository
                factures:
                    mappings:
                        id: ~
                        montantEmis: ~
                        montantRecu: ~
                        montantEmisCreances: ~
                        montantEmisRappels: ~
                        statut: ~
                        nombreRappels: ~
                        dateCreation: { type: date}
                        datePayement: { type: date}
                        creances:
                            type: "nested"
                            properties:
                                titre: ~
                                montantEmis: ~
                                montantRecu: ~
                                dateCreation: { type: date}
                        rappels:
                             type: "nested"
                             properties:
                                 montantEmis: ~
                                 montantRecu: ~
                                 dateCreation: { type: date}
                        payement:
                             type: "nested"
                             properties:
                                 montantRecu: ~
                        debiteur:
                             type: "nested"
                             properties:
                                 getOwnerAsString: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Facture
                        provider: ~
                        listener: ~
                        finder: ~
                        repository: AppBundle\Search\Facture\FactureRepository
                payement:
                    mappings:
                        id: ~
                        montantRecu: ~
                        date: { type: date}
                        state: ~
                        idFacture: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Payement
                        provider: ~
                        listener: ~
                        finder: ~
                        repository: AppBundle\Search\Payement\PayementRepository
