lexik_maintenance:
    authorized:
#        path: /path                                                         # Optional. Authorized path, accepts regexs
#        host: your-domain.com                                               # Optional. Authorized domain, accepts regexs
#        ips: ['127.0.0.1', '172.123.10.14']                                 # Optional. Authorized ip addresses
#        query: { foo: bar }                                                 # Optional. Authorized request query parameter (GET/POST)
#        cookie: { bar: baz }                                                # Optional. Authorized cookie
#        route:                                                              # Optional. Authorized route name
#        attributes:                                                         # Optional. Authorized route attributes
    driver:
        #ttl: 3600                                                                  # Optional ttl option, can be not set

         # File driver
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'                # class for file driver
        options: {file_path: %kernel.root_dir%/cache/lock}                         # file_path is the complete path for create the file

         # Shared memory driver
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\ShmDriver'                 # class for shared memory driver

         # MemCache driver
        class: Lexik\Bundle\MaintenanceBundle\Drivers\MemCacheDriver               # class for MemCache driver
        options: {key_name: 'maintenance', host: '%maintenance_host%', port: '%maintenance_port%'}           # need to define a key_name, the host and port

        # Database driver:
        class: 'Lexik\Bundle\MaintenanceBundle\Drivers\DatabaseDriver'             # class for database driver

        # Option 1 : for doctrine
        #options: {connection: custom}                                            # Optional. You can choice an other connection. Without option it's the doctrine default connection who will be used

        # Option 2 : for dsn, you must have a column ttl type datetime in your table.
        #options: {dsn: "mysql:dbname=maintenance;host:localhost", table: maintenance, user: root, password: root}  # the dsn configuration, name of table, user/password

    #Optional. response code and status of the maintenance page
    response:
        code: 503
        status: "Service Temporarily Unavailable"