#pas de prefixe parce que l'on y trouve notamment /login pour se connecter
security:
    resource: "@InterneSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    prefix:   /intranet

finances:
    resource: "@InterneFinancesBundle/Controller/"
    type:     annotation
    prefix:   /intranet/finances

mat:
    resource: "@MatBundle/Controller/"
    type:     annotation
    prefix:   /intranet/materiel

interne_organisation:
    resource: "@InterneOrganisationBundle/Controller/"
    type:     annotation
    prefix:   /intranet/organisation

galerie:
    resource: "@InterneGalerieBundle/Resources/config/routing.yml"

seance_api:
    type:     rest
    resource: "@InterneSeanceBundle/Resources/config/routing_rest.yml"
    prefix:   /intranet/seance-api
    options:
        expose: true

seance:
    resource: "@InterneSeanceBundle/Resources/config/routing.yml"
    prefix:   /intranet/seance

interne_mail:
    resource: "@InterneMailBundle/Resources/config/routing.yml"
    prefix:   /intranet/mail

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


