mat:
    resource: "@MatBundle/Controller/"
    type:     annotation
    prefix:   /interne/materiel

interne_organisation:
    resource: "@InterneOrganisationBundle/Controller/"
    type:     annotation
    prefix:   /interne/organisation

security:
    resource: "@InterneSecurityBundle/Controller/"
    type:     annotation
    prefix:   / #pas de prefixe parce que l'on y trouve notamment /login pour se connecter

app:
    resource: @AppBundle/Controller/
    type:     annotation
    prefix:   /interne

finances:
    resource: "@InterneFinancesBundle/Controller/"
    type:     annotation
    prefix:   /interne/finances

galerie:
    resource: "@InterneGalerieBundle/Resources/config/routing.yml"

seance:
    resource: "@InterneSeanceBundle/Resources/config/routing.yml"
    prefix:   /interne/seance

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
