#pas de prefixe parce que l'on y trouve notamment /login pour se connecter
#app_security_login:
#    path:  /
#    defaults: { _controller: AppBundle:Security:redirectLogin }
#
#app_security_login:
#    path:  /login
#    defaults: { _controller: AppBundle:Security:login }
#
#app_security_logincheck:
#    path:  /login_check
#    defaults: { _controller: AppBundle:Security:login_check }
#
#app_security_logout:
#    path:  /logout
#    defaults: { _controller: AppBundle:Security:logout }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

#mat:
#    resource: "@MatBundle/Controller/"
#    type:     annotation
#    prefix:   /intranet/materiel
#
#interne_organisation:
#    resource: "@InterneOrganisationBundle/Controller/"
#    type:     annotation
#    prefix:   /intranet/organisation
#
#seance_api:
#    type:     rest
#    resource: "@InterneSeanceBundle/Resources/config/routing_rest.yml"
#    prefix:   /intranet/seance-api
#    options:
#        expose: true
#
#seance:
#    resource: "@InterneSeanceBundle/Resources/config/routing.yml"
#    prefix:   /intranet/seance

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


