security:
    providers:
        insiders:
            entity:
                class: Interne\SecurityBundle\Entity\User
                property: username

    encoders:
        Interne\SecurityBundle\Entity\User: plaintext

    firewalls:

        # Firewall principal
        interne:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /intranet

            logout:
                path:   /logout
                target: /login


    access_control:
        - { path: ^/intranet, roles: ROLE_ADMIN}