security:
    providers:
        insiders:
            entity:
                class: Interne\SecurityBundle\Entity\User
                property: username

    encoders:
        Interne\SecurityBundle\Entity\User: plaintext

    firewalls:

        # Firewall principal
        # Sécurise la totalité de l'intranet, c'est-à-dire toute la partie "interne"
        interne:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /interne

            logout:
                path:   /logout
                target: /login


    access_control:
        - { path: ^/interne, roles: ROLE_USER}
