# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    listing:
        class: AppBundle\Utils\Listing\Lister
        arguments:
            - @session
            - @doctrine.orm.entity_manager

    parser:
        class: AppBundle\Utils\Accessor\Parser
        arguments:
            - @doctrine.orm.entity_manager

    jsonParser:
        class: AppBundle\Utils\Data\JsonParser
        arguments:
            - @router

    pdf:
        class: AppBundle\Utils\Export\Pdf
        arguments:
            - @kernel

    email:
        class: AppBundle\Utils\Email\Email

    listeEnvoi:
        class: AppBundle\Utils\Envoi\ListeEnvoi
        arguments:
            - @session
            - @doctrine.orm.entity_manager

    parametres:
        class: AppBundle\Utils\Parametre\Parametres
        arguments:
            - @kernel




    # Twig
    # Extensions twig qui permettent de mettre en place des filtres
    # personnalisés
    app.twig.boolean_filter:
        class: AppBundle\Twig\BooleanFilter
        tags:
            - { name: twig.extension }

    app.twig.genre_filter:
        class: AppBundle\Twig\GenreFilter
        tags:
            - { name: twig.extension }

    app.twig.validation_extension:
        class: AppBundle\Twig\ValidationExtension
        arguments:
            - @router
        tags:
            - { name: twig.extension }

    app.twig.parser_extension:
        class: AppBundle\Twig\ParserExtension
        arguments:
            - @parser
        tags:
            - { name: twig.extension }

    app.twig.visual:
        class: AppBundle\Twig\VisualExtension
        tags:
            - { name: twig.extension }



    # Types
    # Ces services sont des FormTypes qui permettent d'accéder
    # aux types personnalisés plus facilement
    app.type.datepicker:
        class: AppBundle\Field\DatePickerType
        tags:
            - { name: form.type, alias: datepicker }

    app.type.semantic:
        class: AppBundle\Field\SemanticType
        tags:
            - { name: form.type, alias: semantic }

    app.type.genre:
        class: AppBundle\Field\GenreType
        tags:
            - { name: form.type, alias: genre }

    app.type.boolean:
            class: AppBundle\Field\BooleanType
            tags:
                - { name: form.type, alias: boolean }
