# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    listing:
        class: AppBundle\Utils\Listing\Lister
        arguments:
            - @session
            - @doctrine.orm.entity_manager

    #parser:
    #    class: AppBundle\Utils\Accessor\Parser
    #    arguments:
    #        - @doctrine.orm.entity_manager

    cache:
        class: AppBundle\Utils\Cache\FileSystemCache
        arguments:
            - "%kernel.cache_dir%"

    jsonParser:
        class: AppBundle\Utils\Data\JsonParser
        arguments:
            - @router

    pdf:
        class: AppBundle\Utils\Export\Pdf
        arguments:
            - @kernel

    email:
        class: AppBundle\Utils\Email\Email


    #recuperation des parametres de l'application gérés par les utilisateurs
    parametres:
        class: AppBundle\Utils\Parametre\Parametres
        arguments:
            - @doctrine.orm.entity_manager
            - %intranet_parameters%

    #Permet le rendu des annotation @menu
    menu:
        class: AppBundle\Utils\Menu\MenuRenderer
        arguments:
            - @annotations.reader
            - @kernel
            - @router

    #Contient les listes stockée en session
    list_storage:
        class: AppBundle\Utils\ListUtils\ListStorage
        arguments:
            - @session
            - @doctrine.orm.entity_manager

    #Contient tout les listes crée: - Permet d'appeler les listes depuis twig - Permet d'appeler les liste depuis une route
    list_caller:
        class: AppBundle\Controller\ListCallerController
        arguments:
            - @service_container


    #Sauve un document uploader dans le bon dossier
    document_storage:
        class: AppBundle\Utils\Document\DocumentStorage
        arguments:
            - %upload_documents_dir%

    #permet de faire un pdf avec une facture
    app.facture_printer:
        class: AppBundle\Utils\Finances\FacturePrinter
        arguments:
            - @doctrine.orm.entity_manager
            - @parametres
            - @pdf

    #permet la gestion de la facturation
    app.facturation:
        class: AppBundle\Utils\Finances\Facturation
        arguments:
            - @app.repository.facture

    #permet la gestion des notifications de façon simplifiée
    app.notification_bag:
        class: AppBundle\Utils\SessionTools\NotificationBag
        arguments:
            - @session


    #permet de checker la validité d'un payement
    app.payement.check:
        class: AppBundle\Utils\Finances\PayementCheck
        arguments:
            - @app.repository.facture
            - @app.repository.payement
            - @app.facture.auto_distribution

    #permet de répartire l'argent dans recu pour une facture de facon automatique dans ses créance et rappel
    app.facture.auto_distribution:
        class: AppBundle\Utils\Finances\FactureAutoDistribution
        arguments:
            - @app.repository.facture

    #permet l'analize des entities versionnées
    app.audit.analizer:
        class: AppBundle\Utils\EntityAudit\AuditAnalizer
        arguments:
            auditReader: @simplethings_entityaudit.reader
            em: @doctrine.orm.entity_manager


    # Twig
    # Extensions twig qui permettent de mettre en place des filtres
    # personnalisés
    app.twig.validation_extension:
        class: AppBundle\Twig\ValidationExtension
        arguments:
            - @router
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

    app.twig.groupby:
        class: AppBundle\Twig\GroupByExtension
        tags:
            - { name: twig.extension }

    app.twig.app_extension:
        class: AppBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }

    app.twig.finances_extension:
        class: AppBundle\Twig\FinancesExtension
        tags:
            - { name: twig.extension }


    # Types
    # Ces services sont des FormTypes qui permettent d'accéder
    # aux types personnalisés plus facilement
    app.type.datepicker:
        class: AppBundle\Field\DatePickerType
        tags:
            - { name: form.type, alias: datepicker }

    app.type.semantic:
        class: AppBundle\Field\SemanticType
        tags:
            - { name: form.type, alias: semantic }

    app.type.genre:
        class: AppBundle\Field\GenreType
        tags:
            - { name: form.type, alias: genre }

    app.type.boolean:
        class: AppBundle\Field\BooleanType
        tags:
            - { name: form.type, alias: boolean }

    app.type.remarque_accordion:
        class: AppBundle\Field\RemarqueAccordionType
        tags:
            - { name: form.type, alias: remarque_accordion }

    app.type.dynamic_collection:
        class: AppBundle\Field\DynamicCollectionType
        tags:
            - { name: form.type, alias: dynamic_collection }



    # EVENTS LISTENER AND SUBSCRIBER
#    app.dynamic_relation_subscriber:
#        class: AppBundle\EventSubscriber\DynamicRelationSubscriber
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }


    #subscriber durant l'authentification.
    app.subscriber.authentication:
        class: AppBundle\EventSubscriber\AuthenticationSubscriber
        arguments:
            user_repository: "@app.repository.user"
        tags:
            - { name: kernel.event_subscriber }


#    security.access.membre_voter:
#            class:      AppBundle\Voters\MembreVoter
#            public:     false
#            tags:
#                - { name: security.voter }
#
#    security.access.famille_voter:
#        class:      AppBundle\Voters\FamilleVoter
#        public:     false
#        tags:
#            - { name: security.voter }
#
#    security.access.groupe_voter:
#        class:      AppBundle\Voters\GroupeVoter
#        public:     false
#        tags:
#            - { name: security.voter }
#
#    security.access.role_voter:
#        class:      AppBundle\Voters\RoleHierarchyVoter
#        public:     false
#        tags:
#            - { name: security.voter }
#        arguments:
#            - @doctrine.orm.entity_manager
#            - @session

    # Serializer dedicated for the entities of the app
    serializer.membre:
        class: AppBundle\Utils\Serializer\MembreSerializer
        arguments:
            - @jms_serializer
    serializer.user:
        class: AppBundle\Utils\Serializer\UserSerializer
        arguments:
            - @jms_serializer


    # SECURITY
    # Provider for user (used in authentication proccess)
    app.user.provider:
        class: AppBundle\Security\UserProvider
        arguments:
            repository: "@app.repository.user"
            hierarchy: "@app.role.hierarchy"

    # Role Hierachy manager
    app.role.hierarchy:
        class: AppBundle\Security\RoleHierarchy
        arguments:
            builder: "@app.role.hierarchy.builder"

    # Role Hierachy builder
    app.role.hierarchy.builder:
        class: AppBundle\Security\RoleHierarchyBuilder
        arguments:
            role_hierarchy: "%role_hierarchy%"
            role_description: "%role_description%"



