interne_facture_creance_add_ajax:
    path:     /add_ajax
    defaults: { _controller: InterneFactureBundle:Creance:addAjax }
    options:
            expose: true

interne_facture_creance_facturation_ajax:
    path:     /facturation_ajax
    defaults: { _controller: InterneFactureBundle:Creance:facturationAjax }
    options:
            expose: true

interne_facture_creance_add_creance_to_listing_ajax:
    path:     /add_creance_to_listing_ajax
    defaults: { _controller: InterneFactureBundle:Creance:addCreanceToListingAjax }
    options:
            expose: true

interne_facture_creance_delete_ajax:
    path:     /delete_ajax
    defaults: { _controller: InterneFactureBundle:Creance:deleteAjax }
    options:
            expose: true