interne_facture_create:
    path:     /create
    defaults: { _controller: InterneFactureBundle:Facture:create }

interne_facture_show:
    path:     /show/{id}
    defaults: { _controller: InterneFactureBundle:Facture:show }

interne_facture_update:
    path:     /update/{id}
    defaults: { _controller: InterneFactureBundle:Facture:update }

interne_facture_show_all:
    path:     /showall
    defaults: { _controller: InterneFactureBundle:Facture:showAll }

interne_facture_delete:
    path:     /delete/{id}
    defaults: { _controller: InterneFactureBundle:Facture:delete }

interne_facture_test:
    path:     /test
    defaults: { _controller: InterneFactureBundle:Facture:test }

interne_facture_delete_ajax:
    path:     /delete_ajax
    defaults: { _controller: InterneFactureBundle:Facture:deleteAjax }
    options:
            expose: true