<?php

namespace Interne\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValidatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidatorRepository extends EntityRepository
{
}
