public:
    resource: Interne\GalerieBundle\Controller\PublicController
    type:     annotation
    prefix:   /galerie

adminGalerie:
    resource: Interne\GalerieBundle\Controller\GalerieAdminController
    type:     annotation
    prefix:   /interne/galerie

adminDossier:
    resource: Interne\GalerieBundle\Controller\DossierAdminController
    type:     annotation
    prefix:   /interne/galerie/dossier