parameters:
    #ces parametres peuvent être changée par le client, il sont donc modifiable en cours d'utilisation
    #il s'agit donc du fichier d'initialisation de ces parametre qui sont ensuite stocké en DB
    intranet_parameters:
            app_name:
                type: text
                options:
                    label: 'Nom de la platforme'
                    default: Intranet
                    description: 'Il s agit du nom que vous souhaitez donner à cet intranet'
            group_name:
                type: text
                options:
                    label: 'Nom du groupe scout'
                    default: 'Nom du groupe'
            group_address:
                type: textaera
                options:
                    label: 'Adresse postale du groupe scout'
                    default: 'Adresse postale du groupe scout'
            no_reply_email:
                type: email
                options:
                    default: noreply@dbscout.ch
                    label: 'Adresse email d''expedition automatique'
            group_logo:
                type: png
                options:
                    label: 'Logo du groupe scout'
                    max: 50k
            finances_impression_cpp_bvr:
                type: text
                options:
                    label: 'Numéro de compte CCP (BVR)'
                    default: 10-1915-8
            finances_impression_texte_facture:
                type: text
                options:
                    label: 'Texte présent sur les factures'
                    default: 'Text à écrire'
            finances_impression_affichage_montant:
                type: choice
                options:
                    label: 'Affichage du montant sur les factures'
                    default: false
                    choices:
                        -
                            'true': oui
                        -
                            'false': non
            finances_impression_mode_payement:
                type: choice
                options:
                    label: 'Choix du mode de payement'
                    default: BV
                    choices:
                        -
                            BV: BV
                        -
                            BVR: BVR