parameters:
    # Liste des roles nécéssitant une explication
    security.role_description:
        ROLE_USER: "Role minimum permetant l'accès à l'application"
        ROLE_ADMIN: "administrateur"
        ROLE_FINANCE: "gestion des finances"
        ROLE_SECURITY: "Gestion des utilisateurs du site, doit d'accès et privilège"
        ROLE_PARAMETER: "Gestion des parametres dynamique de l'application"
        ROLE_STRUCTURE: "Gestion de la structure des groupes, fonctions, etc."

    # Hierachie des roles
    # /!\ final roles according to CRUD standard
    security.role_hierarchy:
        ROLE_ADMIN:
            ROLE_USER:
            ROLE_FINANCE:
                ROLE_CREANCE:
                    ROLE_CREANCE_CREATE:
                    ROLE_CREANCE_UPDATE:
                    ROLE_CREANCE_READ:
                    ROLE_CREANCE_DELETE:
                ROLE_FACTURE:
                ROLE_PAYEMENT:
            ROLE_STRUCTURE:
                ROLE_DISTINCTION:
                    ROLE_DISTINCTION_CREATE:
                    ROLE_DISTINCTION_UPDATE:
                    ROLE_DISTINCTION_READ:
                    ROLE_DISTINCTION_DELETE:
                ROLE_CATEGORIE:
                    ROLE_CATEGORIE_CREATE:
                    ROLE_CATEGORIE_UPDATE:
                    ROLE_CATEGORIE_READ:
                    ROLE_CATEGORIE_DELETE:
            ROLE_SECURITY:
            ROLE_PARAMETER:
            ROLE_MODIFICATION:
