#todo migrer les services requit par l'app ici...c'est plus logique

services:
    #SECURITY
    # Provider for user (used in authentication proccess)
    app.user.provider:
        class: AppBundle\Security\UserProvider
        arguments:
            repository: "@app.repository.user"
            hierarchy: "@app.role.hierarchy"

    # Role Hierachy manager
    app.role.hierarchy:
        class: AppBundle\Security\RoleHierarchy
        arguments:
            builder: "@app.role.hierarchy.builder"

    # Role Hierachy builder
    app.role.hierarchy.builder:
        class: AppBundle\Security\RoleHierarchyBuilder
        arguments:
            role_hierarchy: "%security.role_hierarchy%"
            role_description: "%security.role_description%"


    excel_generator:
        class:  AppBundle\Utils\Export\Excel\ExcelGenerator
        arguments:
            - "@app.twig.app_extension"
            - "@twig"

    excel.renderer.groupe:
        class: AppBundle\Utils\Excel\Renderer\GroupeRenderer
        arguments:
            - "@doctrine.orm.entity_manager"


    #FORMULAIRES NECESSITANT DE L'INJECTION
    app.form.field.date:
        class: AppBundle\Field\DateType
        arguments:
            format: "%format_date_icu%"
        tags:
            - { name: form.type }
