#todo migrer les services requit par l'app ici...c'est plus logique

services:

    excel_generator:
        class:  AppBundle\Utils\Export\Excel\ExcelGenerator
        arguments:
            - "@app.twig.app_extension"
            - "@twig"

    excel.renderer.groupe:
        class: AppBundle\Utils\Excel\Renderer\GroupeRenderer
        arguments:
            - "@doctrine.orm.entity_manager"


    #FORMULAIRES NECESSITANT DE L'INJECTION
    app.form.field.date:
        class: AppBundle\Field\DateType
        arguments:
            format: "%format_date_icu%"
        tags:
            - { name: form.type }
