#todo migrer les services requit par l'app ici...c'est plus logique

services:
    #conversion des listes en excel
    app.list_to_excel:
        class: AppBundle\Utils\ListUtils\ListToExcel
        arguments:
            - "%cache_temporary_documents_dir%"
