services:

    # VOTERS
    app.voter.user:
        class:      AppBundle\Voters\UserVoter
        arguments:
            decisionManager: "@security.access.decision_manager"
        public:     false #small boost performence
        tags:
            - { name: security.voter }

    app.voter.categorie:
        class:      AppBundle\Voters\CategorieVoter
        arguments:
            decisionManager: "@security.access.decision_manager"
        public:     false #small boost performence
        tags:
            - { name: security.voter }

    app.voter.creance:
        class:      AppBundle\Voters\CreanceVoter
        arguments:
            decisionManager: "@security.access.decision_manager"
        public:     false #small boost performence
        tags:
            - { name: security.voter }