<?php

namespace AppBundle\Entity;

use \Doctrine\ORM\EntityRepository;

/**
 * FamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleRepository extends EntityRepository
{
    /**
     * @param array $idArray
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function queryByIds($idArray)
    {
        $query = $this->createQueryBuilder('f')
            ->where('f.id IN (:id)')
            ->setParameter('id', $idArray);
        return $query;
    }

}
