
services:
    security.userInfo:
        class    : Interne\SecurityBundle\Services\UserInfo
        arguments:
            - @security.context
            - @doctrine.orm.entity_manager

#    security.entityValidator:
#        class:    Interne\SecurityBundle\Validator\EntityValidator
#        arguments: ["@service_container"]
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
