parameters:

services:

    security.access.membre_voter:
        class:      Interne\SecurityBundle\Voters\MembreVoter
        public:     false
        tags:
            - { name: security.voter }

    security.access.famille_voter:
        class:      Interne\SecurityBundle\Voters\FamilleVoter
        public:     false
        tags:
            - { name: security.voter }

    security.access.groupe_voter:
        class:      Interne\SecurityBundle\Voters\GroupeVoter
        public:     false
        tags:
            - { name: security.voter }

    security.access.role_hierarchy_voter:
        class:      Interne\SecurityBundle\Voters\RoleHierarchyVoter
        public:     false
        tags:
            - { name: security.voter }