parameters:

services:

    security.access.membre_voter:
        class:      Interne\SecurityBundle\Voters\MembreVoter
        public:     false
        tags:
            - { name: security.voter }

    security.access.famille_voter:
        class:      Interne\SecurityBundle\Voters\FamilleVoter
        public:     false
        tags:
            - { name: security.voter }

    security.access.groupe_voter:
        class:      Interne\SecurityBundle\Voters\GroupeVoter
        public:     false
        tags:
            - { name: security.voter }

    security.access.role_voter:
        class:      Interne\SecurityBundle\Voters\RoleHierarchyVoter
        public:     false
        tags:
            - { name: security.voter }
        arguments:
            - @doctrine.orm.entity_manager
            - @session

    security.listener.authentification.successful:
        class: Interne\SecurityBundle\Events\AuthentificationListener
        arguments:
            - @security.token_storage
            - @doctrine.orm.entity_manager
            - @listing
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }