<?php

namespace Interne\OrganisationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    /**
     * @param $startPoint
     * @param $nbResults
     * @return array
     */
    public function findForPaging($startPoint,$nbResults)
    {
        $queryBuilder = $this->createQueryBuilder('news')
            ->orderBy('news.id','DESC')
            ->setMaxResults($nbResults)
            ->setFirstResult($startPoint);
        return $queryBuilder->getQuery()->getResult();
    }
}
