<?php

namespace Interne\FinancesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreanceToMembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreanceToMembreRepository extends EntityRepository
{

    public function findByOwner($nom,$prenom)
    {
        $queryBuilder = $this->createQueryBuilder('creance');
        $queryBuilder->leftJoin('AppBundle\Entity\Membre', 'membre', 'WITH', 'membre.id = creance.membre');
        $queryBuilder->leftJoin('AppBundle\Entity\Famille', 'famille', 'WITH', 'membre.id = membre.famille');

        if ($prenom != null) {

            $queryBuilder->andWhere($queryBuilder->expr()->like('membre.prenom',$queryBuilder->expr()->literal('%'.$prenom.'%')) );
        }

        if ($nom != null) {

            $queryBuilder->andWhere($queryBuilder->expr()->like('famille.nom',$queryBuilder->expr()->literal('%'.$nom.'%')) );

        }

        $results = $queryBuilder->getQuery()->getResult();

        $idAarry = array();

        foreach($results as $result)
        {
            array_push($idAarry,$result->getId());
        }

        return $idAarry;

    }
}