<?php

namespace Interne\FinancesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends EntityRepository
{
    /*
     * cette fonction est utilisée par le formulaire de recherche de facture.
     * on crée une requete custom.
     */
    public function findBySearch($facture,$searchParameters = null)
    {
        //on crée un nouvelle requete qui sera custom
        $queryBuilder = $this->createQueryBuilder('facture');

        /*
         * Elements de recherche contenu dans le formulaire de facture standard
         */

        $parameter = $facture->getId();
        if($parameter != null)
        {
            $queryBuilder->andWhere('facture.id = :id')->setParameter('id', $parameter);
        }

        $parameter = $facture->getStatut();
        if($parameter != null)
        {
            $queryBuilder->andWhere('facture.statut = :statut')->setParameter('statut', $parameter);
        }

        $parameter = $facture->getDateCreation();
        if($parameter != null)
        {
            $queryBuilder->andWhere('facture.dateCreation = :dateCreation')
                ->setParameter('dateCreation', $parameter);
        }

        $parameter = $facture->getDatePayement();
        if($parameter != null)
        {
            $queryBuilder->andWhere('facture.datePayement = :datePayement')
                ->setParameter('datePayement', $parameter);
        }


        /*
         *
         * Elements de recherche spécifique qui permet d'affiner la recherche.
         *
         */

        if($searchParameters != null) {


            $parameter = $searchParameters['dateCreationMaximum'];
            if ($parameter != null) {
                $queryBuilder->andWhere('facture.dateCreation <= :dateCreationMaximum')
                    ->setParameter('dateCreationMaximum', $parameter);
            }
            $parameter = $searchParameters['dateCreationMinimum'];
            if ($parameter != null) {
                $queryBuilder->andWhere('facture.dateCreation >= :dateCreationMinimum')
                    ->setParameter('dateCreationMinimum', $parameter);
            }

            $parameter = $searchParameters['datePayementMaximum'];
            if ($parameter != null) {
                $queryBuilder->andWhere('facture.datePayement <= :datePayement')
                    ->setParameter('datePayement', $parameter);
            }

            $parameter = $searchParameters['datePayementMinimum'];
            if ($parameter != null) {
                $queryBuilder->andWhere('facture.datePayement >= :datePayement')
                    ->setParameter('datePayement', $parameter);
            }

            /*
             * Activer la jointure uniquement si un des parametres de recherche
             * concerne les rappels. Sinon il y a exculusion direct des factures
             * sans rappel.
             */


            /*

            $queryBuilder //, 'WITH', 'facture.id = rappel.facture');
            ->addSelect('COUNT(rappel) as nrappel')
                //->from('InterneFinancesBundle:Rappel','rappel')
                ->innerJoin('facture.rappels', 'rappel')
              ->GroupBy('facture')
                ->having('nrappel = 1');
            ;

            */


          // $queryBuilder->andWhere($queryBuilder->expr()->eq($queryBuilder->expr()->count('facture.rappels'),2));



        }


            /*
             * Jointure avec les éléments de recherche contenu dans la partie cérance
             */
            $queryBuilder->innerJoin('Interne\FinancesBundle\Entity\Creance', 'creance', 'WITH', 'facture.id = creance.facture');

            //On récupère la créance contenu dans la facture
            $creances = $facture->getCreances();
            $creance = $creances[0];

            //On recherche les créances qui corresponde la créance contenu dans la facture
            $creances = $this->getEntityManager()->getRepository('InterneFinancesBundle:Creance')->findBySearch($creance);

            //On crée la liste des ids de tout les créances trouvée
            $arrayIds = array();
            foreach($creances as $creance)
            {
                array_push($arrayIds,$creance->getId());
            }
            //On cherche tout les factures liées aux créances trouvée.
            $queryBuilder->andWhere('creance.id IN (:ids)')->setParameter('ids', array_values($arrayIds));


        return $queryBuilder->getQuery()->getResult();



    }

    public function findFactureOuverteAtDateTime(\DateTime $date)
    {
        //on crée un nouvelle requete qui sera custom
        $queryBuilder = $this->createQueryBuilder('facture');

        $queryBuilder->andWhere('facture.dateCreation <= :dateCreation')
            ->setParameter('dateCreation', $date);

        $queryBuilder->orWhere('facture.datePayement >= :datePayement')->setParameter('datePayement', $date);

        $queryBuilder->orWhere('facture.datePayement = :datePayement')->setParameter('datePayement', null);

        return $queryBuilder->getQuery()->getResult();
    }

    public function findFacturePayeeBetweenDates(\DateTime $startDate, \DateTime $endDate)
    {
        //on crée un nouvelle requete qui sera custom
        $queryBuilder = $this->createQueryBuilder('facture');
        $queryBuilder->andWhere('facture.datePayement >= :startDate')->setParameter('startDate', $startDate);
        $queryBuilder->andWhere('facture.datePayement <= :endDate')->setParameter('endDate', $endDate);

        return $queryBuilder->getQuery()->getResult();
    }

    public function test(\DateTime $date)
    {
        //on crée un nouvelle requete qui sera custom
        $queryBuilder = $this->createQueryBuilder('facture');

        $queryBuilder->andWhere('facture.dateCreation <= :dateCreation')
            ->setParameter('dateCreation', $date);

        $queryBuilder->orWhere('facture.datePayement >= :datePayement')->setParameter('datePayement', $date);

        $queryBuilder->orWhere('facture.datePayement = :datePayement')->setParameter('datePayement', null);




        return $queryBuilder->getQuery()->getScalarResult();
    }


}
