<?php

namespace Interne\FinancesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends EntityRepository
{
    /*
     * cette fonction est utilisée par le formulaire de recherche de facture.
     * on crée une requete custom.
     */
    public function findBySearch($facture,$searchParameters = null)
    {
        //on crée un nouvelle requete qui sera custom
        $queryBuilder = $this->createQueryBuilder('facture');


        $queryBuilder->leftJoin('Interne\FinancesBundle\Entity\Creance', 'creance', 'WITH', 'facture.id = creance.facture');
        $queryBuilder->GroupBy('facture');
        $queryBuilder->leftJoin('Interne\FinancesBundle\Entity\Rappel', 'rappel', 'WITH', 'facture.id = rappel.facture');
        $queryBuilder->GroupBy('facture');

        $queryBuilder->leftJoin('AppBundle\Entity\Membre', 'membre', 'WITH', 'membre.id = facture.membre');
        $queryBuilder->GroupBy('facture');
        $queryBuilder->leftJoin('AppBundle\Entity\Famille', 'familleDuMembre', 'WITH', 'membre.id = membre.famille');
        $queryBuilder->GroupBy('membre');
        $queryBuilder->leftJoin('AppBundle\Entity\Famille', 'famille', 'WITH', 'famille.id = facture.famille');
        $queryBuilder->GroupBy('facture');

        /*
         * Elements de recherche contenu dans le formulaire de facture standard
         */

        $parameter = $facture->getId();
        if($parameter != null)
        {
            $queryBuilder->andWhere('facture.id = :id')->setParameter('id', $parameter);
        }

        $parameter = $facture->getStatut();
        if($parameter != null)
        {
            $queryBuilder->andWhere('facture.statut = :statut')->setParameter('statut', $parameter);
        }

        $parameter = $facture->getDateCreation();
        if($parameter != null)
        {
            $queryBuilder->andWhere('facture.dateCreation = :dateCreation')
                ->setParameter('dateCreation', $parameter);
        }

        $parameter = $facture->getDatePayement();
        if($parameter != null)
        {
            $queryBuilder->andWhere('facture.datePayement = :datePayement')
                ->setParameter('datePayement', $parameter);
        }


        /*
         *
         * Elements de recherche spécifique qui permet d'affiner la recherche.
         *
         */

        if($searchParameters['facture'] != null) {


            $parameter = $searchParameters['facture']['dateCreationMaximum'];
            if ($parameter != null) {
                $queryBuilder->andWhere('facture.dateCreation <= :dateCreationMaximum')
                    ->setParameter('dateCreationMaximum', $parameter);
            }
            $parameter = $searchParameters['facture']['dateCreationMinimum'];
            if ($parameter != null) {
                $queryBuilder->andWhere('facture.dateCreation >= :dateCreationMinimum')
                    ->setParameter('dateCreationMinimum', $parameter);
            }

            $parameter = $searchParameters['facture']['datePayementMaximum'];
            if ($parameter != null) {
                $queryBuilder->andWhere('facture.datePayement <= :datePayement')
                    ->setParameter('datePayement', $parameter);
            }

            $parameter = $searchParameters['facture']['datePayementMinimum'];
            if ($parameter != null) {
                $queryBuilder->andWhere('facture.datePayement >= :datePayement')
                    ->setParameter('datePayement', $parameter);
            }

            $parameter = $searchParameters['facture']['nombreRappel'];
            if ($parameter != null) {
                if(intval($parameter) > 0)
                {
                    $queryBuilder
                        ->andHaving('COUNT(rappel) = :nbrappel')
                        //->andWhere('SIZE(facture.rappels) = 0');
                        ->setParameter('nbrappel',$parameter);
                }
                else
                {
                    //$queryBuilder->andWhere('SIZE(facture.rappels) = 0');
                    $queryBuilder->andWhere($queryBuilder->expr()->isNull('facture.rappels'));
                }

                //TODO: ne marche par pour une recherche sur 0 rappel

            }



            if($searchParameters['facture']['membrePrenom'] != null)
            {
                $parameter = $searchParameters['facture']['membrePrenom'];
                if ($parameter != null) {
                    $queryBuilder->andWhere($queryBuilder->expr()->like('membre.prenom',$queryBuilder->expr()->literal('%'.$parameter.'%')) );
                }
            }
            if($searchParameters['facture']['membreNom'] != null)
            {
                $parameter = $searchParameters['facture']['membreNom'];
                if ($parameter != null) {
                    $queryBuilder->andWhere($queryBuilder->expr()->like('familleDuMembre.nom',$queryBuilder->expr()->literal('%'.$parameter.'%')) );
                }
            }
            if($searchParameters['facture']['familleNom'] != null)
            {

                $parameter = $searchParameters['facture']['familleNom'];
                if ($parameter != null) {
                    $queryBuilder->andWhere($queryBuilder->expr()->like('famille.nom',$queryBuilder->expr()->literal('%'.$parameter.'%')) );
                }
            }

            if($searchParameters['facture']['montantEmis'] != null)
            {
                $parameter = $searchParameters['facture']['montantEmis'];

                $queryBuilder->andHaving('SUM(creance.montantEmis) + SUM(rappel.montantEmis) = :sum');

                $queryBuilder->setParameter('sum',$parameter);

                //TODO ca marche seulement pour certaine facture...je sais pas pourquoi.


            }




        }








        if($facture->getCreances()->count() != 0)
        {
            /*
             * Jointure avec les éléments de recherche contenu dans la partie cérance
             */

            //On récupère la créance contenu dans la facture
            $creances = $facture->getCreances();
            $creance = $creances[0];

            //On recherche les créances qui corresponde la créance contenu dans la facture
            $creances = $this->getEntityManager()->getRepository('InterneFinancesBundle:Creance')->findBySearch($creance,$searchParameters,true);

            //On crée la liste des ids de tout les créances trouvée
            $arrayIds = array();
            foreach($creances as $creance)
            {
                array_push($arrayIds,$creance->getId());
            }
            //On cherche tout les factures liées aux créances trouvée.
            $queryBuilder->andWhere('creance.id IN (:ids)')->setParameter('ids', array_values($arrayIds));
        }




        return $queryBuilder->getQuery()->getResult();



    }


    public function findByNombreRappel($nb)
    {
        $queryBuilder = $this->createQueryBuilder('facture')
            ->innerJoin('facture.rappels', 'rappel')
            ->GroupBy('facture')
            ->andHaving('COUNT(rappel) = :nb')
            ->setParameter('nb',$nb);
        return  $queryBuilder->getQuery()->getResult();
    }

    public function getNombreRappelArray()
    {
        /*
         * On commence par chercher le nombre de facture ouvertes.
         * (avec ou sans rappel)
         */
        $queryBuilder = $this->createQueryBuilder('facture')
            ->andWhere('facture.statut = :statut')
            ->setParameter('statut', 'ouverte')
            ->addSelect('COUNT(facture) as nfacture');
        $result =  $queryBuilder->getQuery()->getResult();
        $nbFactureOuverte = $result[0]['nfacture'];


        /*
         * On extrait un tableau contenant le nombre
         * de rappel de chaque facture.
         */
        $queryBuilder = $this->createQueryBuilder('facture')
            ->andWhere('facture.statut = :statut')
            ->setParameter('statut', 'ouverte')
            ->innerJoin('facture.rappels', 'rappel')
            ->GroupBy('facture')
            ->addSelect('COUNT(rappel) as nrappel');
        $resultArray =  $queryBuilder->getQuery()->getResult();
        $nbFactureWithRappel = count($resultArray);


        /*
         * On formate le tableau de réponse:
         * index: nombre de rappel
         * valeur: nombre de facture ayant ce nombre de rappel
         */
        $maxNombreRappel = -1;
        $data = array();
        foreach($resultArray as $result) {
            $nombreRappel = $result['nrappel'];
            if ($nombreRappel > $maxNombreRappel) {
                for ($i = $maxNombreRappel + 1; $i <= $nombreRappel; $i++) {
                    $data[$i] = 0;
                }
                $maxNombreRappel = $nombreRappel;
            }
            $data[$nombreRappel]++;
        }
        $data[0] = $nbFactureOuverte-$nbFactureWithRappel;

        return $data;

    }



}
