<?php

namespace Interne\FinancesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PayementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayementRepository extends EntityRepository
{

    /*
     * cette fonction est utilisée par le formulaire de recherche.
     * on crée une requete custom.
     */
    public function findBySearch($payement)
    {
        //on crée un nouvelle requete qui sera custom
        $queryBuilder = $this->createQueryBuilder('payement');


        $parameter = $payement->getIdFacture();
        if($parameter != null)
        {
            $queryBuilder->andWhere('payement.idFacture = :idFacture')->setParameter('idFacture', $parameter);
        }

        $parameter = $payement->getMontantRecu();
        if($parameter != null)
        {
            $queryBuilder->andWhere('payement.montantRecu = :montantRecu')->setParameter('montantRecu', $parameter);
        }

        $parameter = $payement->getDatePayement();
        if($parameter != null)
        {
            $queryBuilder->andWhere('creance.datePayement = :datePayement')->setParameter('datePayement', $parameter);
        }

        $parameter = $payement->getState();
        if($parameter != null)
        {
            $queryBuilder->andWhere('payement.state = :state')->setParameter('state', $parameter);
        }

        return $queryBuilder->getQuery()->getResult();
    }


    /*
    public function findlast($number)
    {
        $queryBuilder = $this->createQueryBuilder('payement');

        $queryBuilder
        ->add('select', 'payement')
        ->add('orderBy', 'payement.id DESC')
        ->setFirstResult( 0 )
        ->setMaxResults($number);

        return $queryBuilder->getQuery()->getResult();
    }
    */

}
